name: Green Bot

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:

  permissions:
    contents: write   # â† penting biar bisa push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # pakai token bawaan
      - name: Commit daily
        run: |
          echo "$(date)" >> log.txt
          git config --global user.name "Husen"
          git config --global user.email "husenmalik7@gmail.com"
          git add log.txt
          git commit -m "Auto commit: $(date)"
          git push
